

============================== 2022-11-15 15:25:57.465484 | 56c22729-a037-4294-b854-be8efb63a8a7 ==============================
[0m15:25:57.465502 [info ] [MainThread]: Running with dbt=1.3.0
[0m15:25:57.466631 [debug] [MainThread]: running dbt with arguments {'write_json': True, 'use_colors': True, 'printer_width': 80, 'version_check': True, 'partial_parse': True, 'static_parser': True, 'profiles_dir': '/Users/arthurrodriguez/.dbt', 'send_anonymous_usage_stats': True, 'event_buffer_size': 100000, 'quiet': False, 'no_print': False, 'skip_profile_setup': False, 'which': 'init', 'indirect_selection': 'eager'}
[0m15:25:57.467038 [debug] [MainThread]: Tracking: tracking
[0m15:25:57.487735 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f847dec9370>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f847de99bb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f847de99e20>]}
[0m15:26:21.566857 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f847de99ca0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f847de99df0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f847de99bb0>]}
[0m15:26:21.567419 [debug] [MainThread]: Flushing usage events
[0m15:26:22.108993 [error] [MainThread]: Encountered an error:

[0m15:26:22.113546 [error] [MainThread]: Traceback (most recent call last):
  File "/Users/arthurrodriguez/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/dbt/main.py", line 135, in main
    results, succeeded = handle_and_check(args)
  File "/Users/arthurrodriguez/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/dbt/main.py", line 198, in handle_and_check
    task, res = run_from_args(parsed)
  File "/Users/arthurrodriguez/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/dbt/main.py", line 245, in run_from_args
    results = task.run()
  File "/Users/arthurrodriguez/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/dbt/task/init.py", line 313, in run
    project_name = self.get_valid_project_name()
  File "/Users/arthurrodriguez/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/dbt/task/init.py", line 270, in get_valid_project_name
    name = click.prompt("Enter a name for your project (letters, digits, underscore)")
  File "/Users/arthurrodriguez/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/click/termui.py", line 166, in prompt
    value = prompt_func(prompt)
  File "/Users/arthurrodriguez/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/click/termui.py", line 149, in prompt_func
    raise Abort() from None
click.exceptions.Abort



============================== 2022-11-15 15:38:43.090231 | 0b538e1e-10e6-4f3d-affd-1ae352a3ac62 ==============================
[0m15:38:43.090243 [info ] [MainThread]: Running with dbt=1.3.0
[0m15:38:43.091208 [debug] [MainThread]: running dbt with arguments {'write_json': True, 'use_colors': True, 'printer_width': 80, 'version_check': True, 'partial_parse': True, 'static_parser': True, 'profiles_dir': '/Users/arthurrodriguez/.dbt', 'send_anonymous_usage_stats': True, 'event_buffer_size': 100000, 'quiet': False, 'no_print': False, 'skip_profile_setup': False, 'which': 'init', 'indirect_selection': 'eager'}
[0m15:38:43.091744 [debug] [MainThread]: Tracking: tracking
[0m15:38:43.116905 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc094eb8370>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc094e88bb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc094e88e20>]}
[0m15:38:49.707306 [debug] [MainThread]: Starter project path: /Users/arthurrodriguez/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/dbt/include/starter_project
[0m15:46:13.561472 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc0975faee0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc0975faf10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc0975fa790>]}
[0m15:46:13.567956 [debug] [MainThread]: Flushing usage events
[0m15:46:14.276344 [error] [MainThread]: Encountered an error:

[0m15:46:14.285013 [error] [MainThread]: Traceback (most recent call last):
  File "/Users/arthurrodriguez/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/dbt/main.py", line 135, in main
    results, succeeded = handle_and_check(args)
  File "/Users/arthurrodriguez/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/dbt/main.py", line 198, in handle_and_check
    task, res = run_from_args(parsed)
  File "/Users/arthurrodriguez/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/dbt/main.py", line 245, in run_from_args
    results = task.run()
  File "/Users/arthurrodriguez/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/dbt/task/init.py", line 332, in run
    self.create_profile_from_target(adapter, profile_name=project_name)
  File "/Users/arthurrodriguez/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/dbt/task/init.py", line 207, in create_profile_from_target
    self.create_profile_from_profile_template(profile_template, profile_name)
  File "/Users/arthurrodriguez/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/dbt/task/init.py", line 191, in create_profile_from_profile_template
    target = self.generate_target_from_input(prompts, initial_target)
  File "/Users/arthurrodriguez/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/dbt/task/init.py", line 157, in generate_target_from_input
    target[key] = click.prompt(
  File "/Users/arthurrodriguez/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/click/termui.py", line 166, in prompt
    value = prompt_func(prompt)
  File "/Users/arthurrodriguez/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/click/termui.py", line 149, in prompt_func
    raise Abort() from None
click.exceptions.Abort

